# Generated by Django 5.1.3 on 2025-04-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('spinid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserBet',
            fields=[
                ('betid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.JSONField()),
                ('betamount', models.IntegerField(blank=True, null=True)),
                ('earnings', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bet',
            name='user',
        ),
        migrations.DeleteModel(
            name='RouletteSpin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
