# Generated by Django 5.1.3 on 2025-04-22 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('spinid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'roulette',
            },
        ),
        migrations.CreateModel(
            name='Roulette_UserBets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betid', models.CharField(max_length=50)),
                ('betamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chipcount', models.IntegerField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userbets',
            },
        ),
    ]
