# Generated by Django 5.1.3 on 2025-04-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserBets',
            fields=[
                ('userid', models.IntegerField()),
                ('betid', models.AutoField(primary_key=True, serialize=False)),
                ('betamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chipcount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'userbets',
            },
        ),
        migrations.AddField(
            model_name='roulette',
            name='color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Roulette_UserBets',
        ),
    ]
